In [1]:
%%capture
%pip install cupy-cuda12x
%pip install spacy[cuda-autodetect]
%pip install pandas
%pip install ekphrasis

In [2]:
FND_ROOT = "/workspace/rumor-detection"
PLURALISMO_ROOT = f"{FND_ROOT}/datasets/datasets-fnd-pluralismo/OnlyRepliesTree"

In [3]:
import json
import os

import numpy as np
import pandas as pd
import spacy
from ekphrasis.classes.preprocessor import TextPreProcessor
from ekphrasis.classes.tokenizer import SocialTokenizer
from ekphrasis.dicts.emoticons import emoticons

In [4]:
# spacy.require_gpu()

In [5]:
text_processor = TextPreProcessor(
    # terms that will be normalized
    normalize=[
        "url",
        "email",
        "percent",
        "money",
        "phone",
        "user",
        "time",
        "date",
        "number",
    ],
    # terms that will be annotated
    # annotate={"hashtag", "allcaps", "elongated", "repeated", 'emphasis', 'censored'},
    fix_html=True,  # fix HTML tokens
    # corpus from which the word statistics are going to be used
    # for word segmentation
    segmenter="twitter",
    # corpus from which the word statistics are going to be used
    # for spell correction
    # corrector="twitter",
    unpack_hashtags=True,  # perform word segmentation on hashtags
    # unpack_contractions=True,  # Unpack contractions (can't -> can not)
    spell_correct_elong=False,  # spell correction for elongated words
    # select a tokenizer. You can use SocialTokenizer, or pass your own
    # the tokenizer, should take as input a string and return a list of tokens
    tokenizer=SocialTokenizer(lowercase=True).tokenize,
    # list of dictionaries, for replacing tokens extracted from the text,
    # with other expressions. You can pass more than one dictionaries.
    dicts=[emoticons],
)

/home/ismael/.local/lib/python3.11/site-packages/ekphrasis/classes/tokenizer.py:225: FutureWarning: Possible nested set at position 2190
  self.tok = re.compile(r"({})".format("|".join(pipeline)))

Reading twitter - 1grams ...
Reading twitter - 2grams ...
Reading english - 1grams ...

/home/ismael/.local/lib/python3.11/site-packages/ekphrasis/classes/exmanager.py:14: FutureWarning: Possible nested set at position 42
  regexes = {k.lower(): re.compile(self.expressions[k]) for k, v in

In [6]:
def loadAllPosts(PLURALISMO_ROOT):
    """
    Carga todos los posts en formato json desde el directorio ./post.

    Retorna:

    - all_posts, diccionario indexado por tweet id
    - labeled_posts, diccionaro con tweets etiquetados
    - number_of_tweets
    """

    def parseTwitterTree(tree_file):
        tree_data = list()
        for line in tree_file:
            f_first_part, _ = line.split("->")
            _, first_part = f_first_part.split(":")
            first_part = first_part.strip()
            first_part = first_part.replace("'", '"')
            tree_data.append(json.loads(first_part))
        return tree_data

    ### Obtener diccionario con todos los posts
    all_posts = {}
    labels = {}

    subtrees = ["false", "true"]
    subtrees_count = {"false": 0, "true": 0, "imprecise": 0}
    print("all_posts before:")
    print(len(all_posts))
    print(all_posts)

    def retrieve_replies(tweet_info, accumulator):
        if "replies" not in tweet_info or len(tweet_info["replies"]) == 0:
            return accumulator
        else:
            new_accumulator = []
            for tweet_reply in tweet_info["replies"]:
                # reply_id = tweet_reply["id"]
                new_accumulator += retrieve_replies(tweet_reply, [tweet_reply])
            return accumulator + new_accumulator

    for subtree_label in subtrees:
        subtree_file_list = os.listdir(os.path.join(PLURALISMO_ROOT, subtree_label))
        print(
            f"Working with folder {subtree_label} with {len(subtree_file_list)} files"
        )
        for file in subtree_file_list:
            if file.endswith(".json") and not file.endswith("_minf.json"):
                print(f"Working with file {file}")
                try:
                    with open(
                        os.path.join(PLURALISMO_ROOT, subtree_label, file), "r"
                    ) as f:
                        tweet_id = file.split("_")[1].split(".")[0]
                        tweet_dic = json.load(f)
                        for tweet_info in tweet_dic["data"]:
                            if "conversation_id" in tweet_info:
                                if tweet_info["conversation_id"] == str(tweet_id):
                                    all_posts[tweet_id] = tweet_info

                        assert all_posts[tweet_id] is not None

                        nested_replies = retrieve_replies(all_posts[tweet_id], [])
                        print(f"Got {len(nested_replies)} nested replies")
                        for reply in nested_replies:
                            all_posts[reply["id"]] = reply

                        subtrees_count[subtree_label] += 1
                        labels[tweet_id] = subtree_label

                except Exception as exc:
                    print("EXC:")
                    print(exc)

    print("all_posts after:")
    print(len(all_posts))
    print("Tweets etiquetados      : ", len(labels), " ", subtrees_count)

    seqs_lens = []
    labeled_posts = {}
    number_of_tweets = 0
    number_of_retweets = 0
    number_of_invalid_tweets = 0
    no_in_data = 0
    opened_files = 0

    for idx, (tweet_id, subtree_label) in enumerate(labels.items()):
        try:
            if tweet_id in all_posts:
                tree_path = os.path.join(
                    PLURALISMO_ROOT, subtree_label, f"treefile_{tweet_id}_minf.json"
                )
                with open(tree_path) as tree_file:
                    opened_files += 1
                    print(f"File {tree_path} opened correctly")

                    tree_data = parseTwitterTree(tree_file)

                    # ### Remover retweets
                    first = tree_data[0]

                    without_rt = list(filter(lambda t: t[0] != tweet_id, tree_data[1:]))
                    number_of_retweets = number_of_retweets + (
                        len(tree_data[1:]) - len(without_rt)
                    )
                    only_valid = list(filter(lambda t: t[0] in all_posts, without_rt))
                    number_of_invalid_tweets = number_of_invalid_tweets + (
                        len(without_rt) - len(only_valid)
                    )
                    seqs_lens.append(len(only_valid))

                    labeled_posts[tweet_id] = (labels[tweet_id], [first] + only_valid)
                    number_of_tweets = number_of_tweets + 1
            else:
                no_in_data = no_in_data + 1

        except Exception as e:
            print(e)

    assert opened_files == len(labels)

    print(
        "no_in_data              : ", no_in_data
    )  ## están etiquetados, pero no en los post
    print("number_of_tweets        : ", number_of_tweets)
    print("all_posts               : ", len(all_posts))
    print("number_of_retweets      : ", number_of_retweets)  ## En árbol de propagación
    print(
        "number_of_invalid_tweets: ", number_of_invalid_tweets
    )  ## En árbol de propagación

    # La red neuronal necesita un tamaño fijo para la secuencia (datos de entrada)
    # ¿Que largo de secuencia utilizar?
    counts = np.bincount(seqs_lens)  ## seqs_len sólo de los 753
    mode_seq_len = np.argmax(counts)
    mean_seq_len = int(np.mean(seqs_lens))
    min__seq_len = min(seqs_lens)
    max__seq_len = max(seqs_lens)

    print("len(seqs_lens)   : ", len(seqs_lens))
    print("min__seq_len: ", min__seq_len)
    print("max__seq_len: ", max__seq_len)
    print("mean_seq_len: ", mean_seq_len)
    print("mode_seq_len: ", mode_seq_len)

    tree_max_num_seq = mean_seq_len

    return (all_posts, labeled_posts, number_of_tweets, tree_max_num_seq, seqs_lens)

In [7]:
(all_posts, labeled_posts, number_of_tweets, tree_max_num_seq, seqs_lens) = (
    loadAllPosts(PLURALISMO_ROOT)
)

all_posts before:
0
{}
Working with folder false with 210 files
Working with file treefile_1299150874774831106.json
Got 27 nested replies
Working with file treefile_1430686841540390912.json
Got 24 nested replies
Working with file treefile_1435396460804284418.json
Got 44 nested replies
Working with file treefile_1419856439443607558.json
Got 12 nested replies
Working with file treefile_1213539607612215301.json
Got 915 nested replies
Working with file treefile_1394331250333204483.json
EXC:
'1394331250333204483'
Working with file treefile_1251034040746082306.json
Got 14 nested replies
Working with file treefile_1201319587842801664.json
Got 107 nested replies
Working with file treefile_1419760933656739844.json
Got 1098 nested replies
Working with file treefile_1435974369281560580.json
Got 24 nested replies
Working with file treefile_1427082050998181894.json
Got 156 nested replies
Working with file treefile_1337399183708483585.json
Got 156 nested replies
Working with file treefile_1197656125631586304.json
EXC:
'1197656125631586304'
Working with file treefile_1358146903742025730.json
Got 1 nested replies
Working with file treefile_1319766841003331589.json
Got 483 nested replies
Working with file treefile_1337733374736289795.json
Got 24 nested replies
Working with file treefile_1270160451452768257.json
Got 3262 nested replies
Working with file treefile_1296591514576068609.json
Got 51 nested replies
Working with file treefile_1273823342500425728.json
Got 264 nested replies
Working with file treefile_1311354073627717638.json
Got 523 nested replies
Working with file treefile_1365423207864492036.json
Got 2 nested replies
Working with file treefile_1308399326050357259.json
Got 1437 nested replies
Working with file treefile_1364583892058058755.json
Got 51 nested replies
Working with file treefile_1363927198751748097.json
Got 2117 nested replies
Working with file treefile_1341705827548327936.json
Got 1814 nested replies
Working with file treefile_1372916431487172614.json
Got 1690 nested replies
Working with file treefile_1255829387322306561.json
EXC:
'1255829387322306561'
Working with file treefile_1339302185750892547.json
Got 289 nested replies
Working with file treefile_1310923548878397440.json
Got 74 nested replies
Working with file treefile_1304419304989917186.json
Got 720 nested replies
Working with file treefile_1216807639780405249.json
Got 12 nested replies
Working with file treefile_1310647550471557120.json
Got 7 nested replies
Working with file treefile_1294294867703726081.json
Got 26 nested replies
Working with file treefile_1324388104887771143.json
Got 751 nested replies
Working with file treefile_1216821757967044608.json
Got 317 nested replies
Working with file treefile_1396311260656979970.json
Got 929 nested replies
Working with file treefile_1437602416136970242.json
Got 219 nested replies
Working with file treefile_1370392618178387971.json
Got 86 nested replies
Working with file treefile_1273741098536579073.json
EXC:
'1273741098536579073'
Working with file treefile_1216812320418082816.json
Got 21 nested replies
Working with file treefile_1257857126007005193.json
Got 949 nested replies
Working with file treefile_1298293529739964416.json
Got 199 nested replies
Working with file treefile_1377295800477356037.json
Got 11 nested replies
Working with file treefile_1304507979337732096.json
EXC:
'1304507979337732096'
Working with file treefile_1187112564783833088.json
Got 1 nested replies
Working with file treefile_1312497896357470208.json
Got 916 nested replies
Working with file treefile_1278500902064852992.json
Got 215 nested replies
Working with file treefile_1312933260142481410.json
Got 368 nested replies
Working with file treefile_1353160564529311746.json
Got 126 nested replies
Working with file treefile_1357433004663201802.json
Got 1023 nested replies
Working with file treefile_1426134410794086403.json
Got 1950 nested replies
Working with file treefile_1375926748639019014.json
Got 5 nested replies
Working with file treefile_1396251172386836483.json
Got 321 nested replies
Working with file treefile_1411872979206782976.json
Got 386 nested replies
Working with file treefile_1208422130548912129.json
Got 422 nested replies
Working with file treefile_1261893058632826880.json
Got 1192 nested replies
Working with file treefile_1424833779781283841.json
Got 684 nested replies
Working with file treefile_1430386636987244545.json
Got 618 nested replies
Working with file treefile_1450315266487775237.json
Got 54 nested replies
Working with file treefile_1369363281182343174.json
Got 861 nested replies
Working with file treefile_1239264825953456129.json
Got 21 nested replies
Working with file treefile_1376922538090061827.json
Got 283 nested replies
Working with file treefile_1251524085659709441.json
Got 15 nested replies
Working with file treefile_1330920010215264258.json
EXC:
'1330920010215264258'
Working with file treefile_1371696746154356736.json
Got 654 nested replies
Working with file treefile_1248707653364264967.json
Got 140 nested replies
Working with file treefile_1298069740418666497.json
Got 14 nested replies
Working with file treefile_1358057554887270400.json
Got 322 nested replies
Working with file treefile_1266737566889308160.json
Got 226 nested replies
Working with file treefile_1203661693827584000.json
Got 1 nested replies
Working with file treefile_1252466195456045056.json
Got 85 nested replies
Working with file treefile_1291503317173116930.json
Got 33 nested replies
Working with file treefile_1367583722065846278.json
Got 16 nested replies
Working with file treefile_1318403073144913921.json
Got 296 nested replies
Working with file treefile_1301140863742095362.json
Got 170 nested replies
Working with file treefile_1303694410216017921.json
Got 75 nested replies
Working with file treefile_1199954005922848774.json
Got 121 nested replies
Working with file treefile_1198616119592009729.json
Got 436 nested replies
Working with file treefile_1337773251246829569.json
Got 469 nested replies
Working with file treefile_1269654804621479938.json
Got 1025 nested replies
Working with file treefile_1291546987792343043.json
Got 83 nested replies
Working with file treefile_1266021004700274690.json
Got 3569 nested replies
Working with file treefile_1267473234821296134.json
Got 119 nested replies
Working with file treefile_1432166179662143497.json
Got 131 nested replies
Working with file treefile_1280984431776456705.json
Got 1002 nested replies
Working with file treefile_1305179078060838913.json
Got 102 nested replies
Working with file treefile_1291518182126235650.json
EXC:
'1291518182126235650'
Working with file treefile_1309531096372183042.json
Got 9 nested replies
Working with file treefile_1363988459086483456.json
Got 431 nested replies
Working with file treefile_1361821049730584577.json
Got 166 nested replies
Working with file treefile_1299382969480679426.json
Got 1 nested replies
Working with file treefile_1205624164754841600.json
Got 7 nested replies
Working with file treefile_1304037130402922496.json
Got 25 nested replies
Working with file treefile_1281615540130328576.json
Got 129 nested replies
Working with file treefile_1330529128882319371.json
Got 5 nested replies
Working with file treefile_1217249789613658112.json
Got 574 nested replies
Working with file treefile_1450142828802289664.json
Got 60 nested replies
Working with file treefile_1251690304429752323.json
Got 58 nested replies
Working with file treefile_1381268148771565570.json
Got 243 nested replies
Working with file treefile_1195057287288754181.json
Got 291 nested replies
Working with file treefile_1263210686475145216.json
Got 2340 nested replies
Working with file treefile_1251278819828391936.json
Got 183 nested replies
Working with file treefile_1273960627074187265.json
Got 474 nested replies
Working with file treefile_1379077415318720513.json
EXC:
'1379077415318720513'
Working with file treefile_854495625911685120.json
Got 44 nested replies
Working with file treefile_1261109343178706948.json
EXC:
'1261109343178706948'
Working with file treefile_1275073219452522496.json
Got 1622 nested replies
Working with file treefile_1346128641902616576.json
EXC:
'1346128641902616576'
Working with file treefile_1188287266281705472.json
Got 114 nested replies
Working with file treefile_1263812675949211651.json
Got 1179 nested replies
Working with folder true with 236 files
Working with file treefile_1253897522319425542.json
Got 28 nested replies
Working with file treefile_1230922839307538432.json
EXC:
'1230922839307538432'
Working with file treefile_1329441383430680577.json
Got 91 nested replies
Working with file treefile_1364931092382441475.json
Got 2 nested replies
Working with file treefile_1368237437965590531.json
EXC:
'1368237437965590531'
Working with file treefile_1212540991518978048.json
Got 3 nested replies
Working with file treefile_1246815716550066176.json
Got 17 nested replies
Working with file treefile_1437732248133021698.json
Got 795 nested replies
Working with file treefile_1219617184823042050.json
EXC:
'1219617184823042050'
Working with file treefile_1363672564636274689.json
Got 15 nested replies
Working with file treefile_1310982360947716097.json
Got 18 nested replies
Working with file treefile_1374549118752845824.json
Got 43 nested replies
Working with file treefile_1380536389184458752.json
Got 14 nested replies
Working with file treefile_1280133024437489664.json
Got 268 nested replies
Working with file treefile_1309226034210975744.json
Got 141 nested replies
Working with file treefile_1394050046103101443.json
Got 75 nested replies
Working with file treefile_1364762313845317635.json
Got 12 nested replies
Working with file treefile_1278048451868180487.json
Got 238 nested replies
Working with file treefile_1377392891887120385.json
Got 976 nested replies
Working with file treefile_1258926872941006848.json
Got 32 nested replies
Working with file treefile_1247526704358146055.json
Got 9 nested replies
Working with file treefile_1248690536745238535.json
Got 11 nested replies
Working with file treefile_1358636412740984832.json
Got 18 nested replies
Working with file treefile_1348076116188266499.json
Got 13 nested replies
Working with file treefile_1274909414462500865.json
Got 125 nested replies
Working with file treefile_1210750688981962753.json
Got 147 nested replies
Working with file treefile_1417886510674808835.json
Got 203 nested replies
Working with file treefile_1237188811966361600.json
Got 684 nested replies
Working with file treefile_1288301468978761729.json
Got 43 nested replies
Working with file treefile_1270688631686967296.json
Got 9 nested replies
Working with file treefile_1312198210148986880.json
Got 602 nested replies
Working with file treefile_1217850717123334146.json
Got 53 nested replies
Working with file treefile_1245447626344075264.json
Got 35 nested replies
Working with file treefile_1338254643802087425.json
Got 41 nested replies
Working with file treefile_1374083928626237442.json
Got 24 nested replies
Working with file treefile_1354517504761204736.json
Got 130 nested replies
Working with file treefile_1356403198572044297.json
Got 74 nested replies
Working with file treefile_1280522726717956098.json
Got 312 nested replies
Working with file treefile_1386467966414430211.json
Got 16 nested replies
Working with file treefile_1358799834300485635.json
Got 31 nested replies
Working with file treefile_1406695845370736648.json
Got 23 nested replies
Working with file treefile_1382387987728769032.json
Got 307 nested replies
Working with file treefile_1332528772122284033.json
Got 230 nested replies
Working with file treefile_1250466552253685763.json
Got 1251 nested replies
Working with file treefile_1326976861327470592.json
Got 149 nested replies
Working with file treefile_1274921303963840525.json
Got 17 nested replies
Working with file treefile_1437538934347730947.json
Got 30 nested replies
Working with file treefile_1249525325433880580.json
Got 23 nested replies
Working with file treefile_1264106349073498113.json
Got 3 nested replies
Working with file treefile_1320562078319550466.json
Got 97 nested replies
Working with file treefile_1337077691300851716.json
Got 35 nested replies
Working with file treefile_1374025464327602179.json
Got 71 nested replies
Working with file treefile_1389249899632500736.json
Got 2665 nested replies
Working with file treefile_1204572960452952064.json
Got 1360 nested replies
Working with file treefile_1311030087320514560.json
Got 442 nested replies
Working with file treefile_1275567647464271872.json
Got 192 nested replies
Working with file treefile_1368264617340895234.json
Got 21 nested replies
Working with file treefile_1251156989771517957.json
Got 88 nested replies
Working with file treefile_1445401436423131141.json
Got 167 nested replies
Working with file treefile_1257836153933307904.json
Got 108 nested replies
Working with file treefile_1296130156592013312.json
Got 210 nested replies
Working with file treefile_1303620299141926912.json
Got 10644 nested replies
Working with file treefile_1279565155219709954.json
Got 3826 nested replies
Working with file treefile_1359199179059441667.json
EXC:
'1359199179059441667'
Working with file treefile_1367234890731773952.json
Got 2 nested replies
Working with file treefile_1299382794523729920.json
Got 144 nested replies
Working with file treefile_1310257253916737536.json
Got 25 nested replies
Working with file treefile_1191369885806448641.json
Got 99 nested replies
Working with file treefile_1394829454296424451.json
Got 64 nested replies
Working with file treefile_1396669493116612608.json
Got 202 nested replies
Working with file treefile_1237214755129102336.json
Got 285 nested replies
Working with file treefile_1439682136697671683.json
Got 198 nested replies
Working with file treefile_1364993117787738115.json
Got 313 nested replies
Working with file treefile_1268168495126241281.json
Got 594 nested replies
Working with file treefile_1331022275727024130.json
EXC:
'1331022275727024130'
Working with file treefile_1313726020244123649.json
Got 282 nested replies
Working with file treefile_1208308764178292736.json
Got 228 nested replies
Working with file treefile_1307881182097559552.json
Got 200 nested replies
Working with file treefile_1271617183332929536.json
Got 129 nested replies
Working with file treefile_1312208582335582211.json
Got 4 nested replies
Working with file treefile_1307112590724739073.json
Got 33 nested replies
Working with file treefile_1429979674394996738.json
Got 152 nested replies
Working with file treefile_1262533319335575560.json
Got 17 nested replies
Working with file treefile_1189291617238298624.json
Got 2741 nested replies
Working with file treefile_1270390346569187329.json
Got 23 nested replies
Working with file treefile_1425424623533969414.json
EXC:
'1425424623533969414'
Working with file treefile_1250784797737324544.json
Got 56 nested replies
Working with file treefile_1318053189594263552.json
Got 1136 nested replies
Working with file treefile_1362427362701414404.json
Got 6 nested replies
Working with file treefile_1215464348686192640.json
Got 29 nested replies
Working with file treefile_1255985494195949570.json
Got 22 nested replies
Working with file treefile_1251578393579175936.json
Got 2 nested replies
Working with file treefile_1327043661461385218.json
Got 164 nested replies
Working with file treefile_1316094873444003840.json
Got 835 nested replies
Working with file treefile_1293196786761371650.json
Got 1688 nested replies
Working with file treefile_1252337871446573056.json
Got 62 nested replies
Working with file treefile_1446863517819326467.json
Got 46 nested replies
Working with file treefile_1366385502123929600.json
Got 21 nested replies
Working with file treefile_1251600920166780929.json
Got 5 nested replies
Working with file treefile_1241413446375260160.json
Got 14236 nested replies
Working with file treefile_1259185943082414080.json
Got 154 nested replies
Working with file treefile_1307834093518893057.json
Got 514 nested replies
Working with file treefile_1218160910453366785.json
Got 345 nested replies
Working with file treefile_1296451264306348032.json
Got 56 nested replies
Working with file treefile_1208939601039151104.json
Got 3 nested replies
Working with file treefile_1208473946301091840.json
Got 57 nested replies
Working with file treefile_1346030479112331265.json
Got 359 nested replies
Working with file treefile_1217108841575350274.json
EXC:
'1217108841575350274'
Working with file treefile_1246206711209263110.json
Got 206 nested replies
Working with file treefile_1369108855100219395.json
Got 7 nested replies
Working with file treefile_1300188395424165888.json
Got 67 nested replies
Working with file treefile_1249378659489759232.json
Got 73 nested replies
Working with file treefile_1301607903850356737.json
Got 98 nested replies
Working with file treefile_1274005036805341184.json
Got 97 nested replies
Working with file treefile_1370420106057166858.json
Got 189 nested replies
Working with file treefile_1301858951315820546.json
Got 70 nested replies
Working with file treefile_1268649520281370628.json
Got 5 nested replies
Working with file treefile_1296319144447676417.json
Got 825 nested replies
Working with file treefile_1267151214447378432.json
Got 24 nested replies
Working with file treefile_1245713490834345984.json
Got 2 nested replies
Working with file treefile_1266030489250541568.json
Got 919 nested replies
Working with file treefile_1311146562823872512.json
EXC:
'1311146562823872512'
all_posts after:
101045
Tweets etiquetados      :  214   {'false': 100, 'true': 114, 'imprecise': 0}
File /workspace/rumor-detection/datasets/datasets-fnd-pluralismo/OnlyRepliesTree/false/treefile_1299150874774831106_minf.json opened correctly
File /workspace/rumor-detection/datasets/datasets-fnd-pluralismo/OnlyRepliesTree/false/treefile_1430686841540390912_minf.json opened correctly
File /workspace/rumor-detection/datasets/datasets-fnd-pluralismo/OnlyRepliesTree/false/treefile_1435396460804284418_minf.json opened correctly
File /workspace/rumor-detection/datasets/datasets-fnd-pluralismo/OnlyRepliesTree/false/treefile_1419856439443607558_minf.json opened correctly
File /workspace/rumor-detection/datasets/datasets-fnd-pluralismo/OnlyRepliesTree/false/treefile_1213539607612215301_minf.json opened correctly
File /workspace/rumor-detection/datasets/datasets-fnd-pluralismo/OnlyRepliesTree/false/treefile_1251034040746082306_minf.json opened correctly
File /workspace/rumor-detection/datasets/datasets-fnd-pluralismo/OnlyRepliesTree/false/treefile_1201319587842801664_minf.json opened correctly
File /workspace/rumor-detection/datasets/datasets-fnd-pluralismo/OnlyRepliesTree/false/treefile_1419760933656739844_minf.json opened correctly
File /workspace/rumor-detection/datasets/datasets-fnd-pluralismo/OnlyRepliesTree/false/treefile_1435974369281560580_minf.json opened correctly
File /workspace/rumor-detection/datasets/datasets-fnd-pluralismo/OnlyRepliesTree/false/treefile_1427082050998181894_minf.json opened correctly
File /workspace/rumor-detection/datasets/datasets-fnd-pluralismo/OnlyRepliesTree/false/treefile_1337399183708483585_minf.json opened correctly
File /workspace/rumor-detection/datasets/datasets-fnd-pluralismo/OnlyRepliesTree/false/treefile_1358146903742025730_minf.json opened correctly
File /workspace/rumor-detection/datasets/datasets-fnd-pluralismo/OnlyRepliesTree/false/treefile_1319766841003331589_minf.json opened correctly
File /workspace/rumor-detection/datasets/datasets-fnd-pluralismo/OnlyRepliesTree/false/treefile_1337733374736289795_minf.json opened correctly
File /workspace/rumor-detection/datasets/datasets-fnd-pluralismo/OnlyRepliesTree/false/treefile_1270160451452768257_minf.json opened correctly
File /workspace/rumor-detection/datasets/datasets-fnd-pluralismo/OnlyRepliesTree/false/treefile_1296591514576068609_minf.json opened correctly

In [8]:
len(labeled_posts)

214

In [9]:
d = {i: k for i, (k, _) in enumerate(labeled_posts.items())}

In [10]:
regular_seqs_lens = np.array(list(filter(lambda x: x < 320, seqs_lens)))
tree_max_num_seq = int(np.floor(np.mean(regular_seqs_lens)))
tree_max_num_seq

88

In [11]:
labeled_posts["1299150874774831106"]

('false',
 [['1299150874774831106', '0.0'],
  ['1299156214069317636', '1273.0'],
  ['1299156316770963458', '1297.0'],
  ['1299158535805304832', '1826.0'],
  ['1299159444501213184', '2043.0'],
  ['1299163257941487616', '2952.0'],
  ['1299165714604064769', '3538.0'],
  ['1299167915917422593', '4063.0'],
  ['1299170321149329408', '4636.0'],
  ['1299172254580957185', '5097.0'],
  ['1299176131145469952', '6021.0'],
  ['1299177417085509632', '6328.0'],
  ['1299177774389907456', '6413.0'],
  ['1299177779318190080', '6414.0'],
  ['1299177988769165313', '6464.0'],
  ['1299182343505182720', '7502.0'],
  ['1299185107551621120', '8161.0'],
  ['1299192707538190336', '9973.0'],
  ['1299263225922555910', '26786.0'],
  ['1299264335810834432', '27051.0'],
  ['1299287174219739137', '32496.0'],
  ['1299321743216119808', '40738.0'],
  ['1299341645020909568', '45483.0'],
  ['1299347186342395905', '46804.0'],
  ['1299354801143193606', '48620.0'],
  ['1299365560648687616', '51185.0'],
  ['1299366508884303872', '51411.0'],
  ['1299413759233003520', '62676.0']])

In [12]:
len(all_posts)

101045

In [13]:
all_posts["1299150874774831106"]

{'author_id': '34992710',
 'conversation_id': '1299150874774831106',
 'created_at': '2020-08-28T01:04:40.000Z',
 'delta_time': 0.0,
 'id': '1299150874774831106',
 'lang': 'es',
 'replies': [{'author_id': '2334166898',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T18:29:16.000Z',
   'delta_time': 62676.0,
   'id': '1299413759233003520',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter for Android',
   'text': '@hernan_sr Al final y no era q el retiró del 10% nos iba a transformar en un país bananero... Porq resulta q llevabamos un buen rato ya siéndolo 🤦🤦🤦 #CamionerosverguenzaNacional'},
  {'author_id': '1292299328145559552',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T15:21:31.000Z',
   'delta_time': 51411.0,
   'id': '1299366508884303872',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter for Android',
   'text': '@hernan_sr Les queda poco se les derrumbara él imperio que construyeron a base de mentiras y montajes ya nadie les cree asumanlo!'},
  {'author_id': '120589612',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T15:17:45.000Z',
   'delta_time': 51185.0,
   'id': '1299365560648687616',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter for Android',
   'text': '@hernan_sr Y que dice a esto el @GobiernodeChile @min_interior lo desmiente o callara como lo han hecho en muchos otros actos delictuales oficialistas\n\n#AprueboGanaEnOctubre #CamionerosverguenzaNacional #AprueboNuevaConstitucion'},
  {'author_id': '4269741628',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T14:35:00.000Z',
   'delta_time': 48620.0,
   'id': '1299354801143193606',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter for Android',
   'text': '@hernan_sr Y son los mismos que dicen que si cambias la constitución no se solucionan las desigualdades, pero si con una ley represiva se soluciona el conflicto en la Araucanía 😂'},
  {'author_id': '2917425461',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T14:04:44.000Z',
   'delta_time': 46804.0,
   'id': '1299347186342395905',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter for Android',
   'text': '@hernan_sr @Ayinray1 Imagen de hoy 28/08/2020 nube asesina saliendo de fundicion y presente en estratos que se dispersan hacia quintero y puchuncavi llevando el arsenico a la poblacion. Nueva constitucion, cierre fundicion #Apruebo https://t.co/EXOsWBU1fL'},
  {'author_id': '434180616',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T13:42:43.000Z',
   'delta_time': 45483.0,
   'id': '1299341645020909568',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter for iPhone',
   'text': '@hernan_sr @lucho_santis Lógicamente si eres dueño de camiones vas a participará en el paro, o vas a dirigir el paro! Me parece perfecto!!'},
  {'author_id': '1189557694673367045',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T10:06:16.000Z',
   'delta_time': 32496.0,
   'id': '1299287174219739137',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter for Android',
   'text': '@hernan_sr Otro TONGOLELE de la DERECHA!'},
  {'author_id': '1222138618715738112',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T08:35:31.000Z',
   'delta_time': 27051.0,
   'id': '1299264335810834432',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter for Android',
   'text': '@hernan_sr @Alanis_Just Ahora se entiende porque no tiene solución el conflicto es económico antes que https://t.co/xvOslYiGLC arreglan el problema mapuche con el forestal se les acaba el negocio a los camioneros que llevan madera y áridos el Intendente es un https://t.co/3ejpBpUbel ludos'},
  {'author_id': '2220069514',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T08:31:06.000Z',
   'delta_time': 26786.0,
   'id': '1299263225922555910',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter for Android',
   'text': '@hernan_sr Parece que los apruebonados no entienden que el paro no es por arreglarse los bigotes. El paro se hizo para presionar al gobierno a restaurar el estado de derecho. El derecho cont q tenemos todos de circular libres y sin ataques de ningun sector. Se explico bien?'},
  {'author_id': '941662761746124810',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T03:50:53.000Z',
   'delta_time': 9973.0,
   'id': '1299192707538190336',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter for iPad',
   'text': '@hernan_sr Osea que no le conviene el paro, deja de ganar plata.'},
  {'author_id': '1263536882719371267',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T03:20:41.000Z',
   'delta_time': 8161.0,
   'id': '1299185107551621120',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter Web App',
   'text': '@hernan_sr todos estos  son el vomito (putas) de la dictadura'},
  {'author_id': '732255594',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T03:09:42.000Z',
   'delta_time': 7502.0,
   'id': '1299182343505182720',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter for iPhone',
   'text': '@hernan_sr El Care chicha.'},
  {'author_id': '270106992',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T02:52:24.000Z',
   'delta_time': 6464.0,
   'id': '1299177988769165313',
   'in_reply_to_user_id': '34992710',
   'lang': 'und',
   'replies': [],
   'source': 'Twitter for iPhone',
   'text': '@hernan_sr https://t.co/pXDCvWsKlk'},
  {'author_id': '2946933243',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T02:51:33.000Z',
   'delta_time': 6413.0,
   'id': '1299177774389907456',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter for iPhone',
   'text': '@hernan_sr Nada extraño'},
  {'author_id': '61654779',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T02:50:08.000Z',
   'delta_time': 6328.0,
   'id': '1299177417085509632',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter Web App',
   'text': '@hernan_sr Le ofreció desalojo a los pobladores en toma, luego se enfermo de coronavirus cueckkk'},
  {'author_id': '2661299635',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T02:45:01.000Z',
   'delta_time': 6021.0,
   'id': '1299176131145469952',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter Web App',
   'text': '@hernan_sr Este viejo Manoli es igual a "Don Genaro" de la serie Los 80 https://t.co/waZaayrW1y'},
  {'author_id': '1224108097146380288',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T02:29:37.000Z',
   'delta_time': 5097.0,
   'id': '1299172254580957185',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter for Android',
   'text': '@hernan_sr Yyyy fuera yyy fuera https://t.co/g5iupRDdtr'},
  {'author_id': '1041387886728421378',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T02:21:56.000Z',
   'delta_time': 4636.0,
   'id': '1299170321149329408',
   'in_reply_to_user_id': '34992710',
   'lang': 'und',
   'replies': [],
   'source': 'Twitter for Android',
   'text': '@hernan_sr @EPInforma @mentiraslared @alejandramatus @jananeme @CHVNoticias @tv_monica @DMatamala'},
  {'author_id': '158643286',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T02:12:23.000Z',
   'delta_time': 4063.0,
   'id': '1299167915917422593',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [{'author_id': '1123223373079822342',
     'conversation_id': '1299150874774831106',
     'created_at': '2020-08-28T12:23:38.000Z',
     'delta_time': 40738.0,
     'id': '1299321743216119808',
     'in_reply_to_user_id': '158643286',
     'lang': 'und',
     'replies': [],
     'source': 'Twitter for Android',
     'text': '@alb0black @hernan_sr https://t.co/HvOHaf8xKu'},
    {'author_id': '528119606',
     'conversation_id': '1299150874774831106',
     'created_at': '2020-08-28T02:51:34.000Z',
     'delta_time': 6414.0,
     'id': '1299177779318190080',
     'in_reply_to_user_id': '158643286',
     'lang': 'es',
     'replies': [],
     'source': 'Twitter Web App',
     'text': '@alb0black @hernan_sr Y DUEÑO DE FORESTALES, PRESTADOR DE SERVICIOS FORESTALES ETC. ETC.'}],
   'source': 'Twitter Web App',
   'text': '@hernan_sr Mentira, el Presidente Sebastian Piñera no permitiría\nesto.. 🙄'},
  {'author_id': '56131632',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T02:03:38.000Z',
   'delta_time': 3538.0,
   'id': '1299165714604064769',
   'in_reply_to_user_id': '34992710',
   'lang': 'und',
   'replies': [],
   'source': 'Twitter for Android',
   'text': '@hernan_sr @ArchivandoChile'},
  {'author_id': '1693834266',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T01:53:52.000Z',
   'delta_time': 2952.0,
   'id': '1299163257941487616',
   'in_reply_to_user_id': '34992710',
   'lang': 'und',
   'replies': [],
   'source': 'Twitter for Android',
   'text': '@hernan_sr https://t.co/lD5oTQ6mwv'},
  {'author_id': '770129240809414656',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T01:38:43.000Z',
   'delta_time': 2043.0,
   'id': '1299159444501213184',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter Web App',
   'text': '@hernan_sr Está la pura cagada en el gobierno de Piñera, se desató la corrupción.'},
  {'author_id': '720036114447339520',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T01:35:06.000Z',
   'delta_time': 1826.0,
   'id': '1299158535805304832',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter for Android',
   'text': '@hernan_sr Anciano decrépito ,cuanto te que de oxigeno🤷\u200d♀️este fue un trabajo de los pulpos  derechistas ,que no quieren cambio ,pero ya su hora paso dijo la lucerito 👉🤷\u200d♀️🤣'},
  {'author_id': '89714413',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T01:26:17.000Z',
   'delta_time': 1297.0,
   'id': '1299156316770963458',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter for Android',
   'text': '@hernan_sr No tienen verguenza. Que asco me dan todos,  este gobierno es una mierda 💩 #ElPeorGobiernoDeLaHistoria\n #Apruebo\n #ConvencionConstitucional'},
  {'author_id': '26338812',
   'conversation_id': '1299150874774831106',
   'created_at': '2020-08-28T01:25:53.000Z',
   'delta_time': 1273.0,
   'id': '1299156214069317636',
   'in_reply_to_user_id': '34992710',
   'lang': 'es',
   'replies': [],
   'source': 'Twitter for iPhone',
   'text': '@hernan_sr @Eneatipo7 Uy k raro 🙄'}],
 'source': 'Twitter Web App',
 'text': 'Esto es el colmo:\nVíctor Manoli dueño de empresas de camiones, es el Intendente de la Araucanía 🤦\u200d♂️\n¡hablenme de conflicto de INTERÉS!\n#ParoDeFascistas https://t.co/X8TAOvwrWw'}

In [14]:
big_dataframe_dict = {}
for tweet_id, (label, tree_list) in labeled_posts.items():
    print(f"Processing tweet_id: {tweet_id} with label: {label}")

    big_dataframe_dict[tweet_id] = {
        "index": 0,
        "is_root": True,
        "label": label,
        "tree_id": tweet_id,
        "text": all_posts[tweet_id]["text"],
    }

    for idx, reply in enumerate(tree_list[1:], start=1):
        if reply[0] in all_posts:
            big_dataframe_dict[reply[0]] = {
                "index": idx,
                "is_root": False,
                "label": "n/a",
                "tree_id": tweet_id,
                "text": all_posts[reply[0]]["text"],
            }
        else:
            print(f"Reply {reply[0]} not found in all_posts")

Processing tweet_id: 1299150874774831106 with label: false
Processing tweet_id: 1430686841540390912 with label: false
Processing tweet_id: 1435396460804284418 with label: false
Processing tweet_id: 1419856439443607558 with label: false
Processing tweet_id: 1213539607612215301 with label: false
Processing tweet_id: 1251034040746082306 with label: false
Processing tweet_id: 1201319587842801664 with label: false
Processing tweet_id: 1419760933656739844 with label: false
Processing tweet_id: 1435974369281560580 with label: false
Processing tweet_id: 1427082050998181894 with label: false
Processing tweet_id: 1337399183708483585 with label: false
Processing tweet_id: 1358146903742025730 with label: false
Processing tweet_id: 1319766841003331589 with label: false
Processing tweet_id: 1337733374736289795 with label: false
Processing tweet_id: 1270160451452768257 with label: false
Processing tweet_id: 1296591514576068609 with label: false
Processing tweet_id: 1273823342500425728 with label: false
Processing tweet_id: 1311354073627717638 with label: false
Processing tweet_id: 1365423207864492036 with label: false
Processing tweet_id: 1308399326050357259 with label: false
Processing tweet_id: 1364583892058058755 with label: false
Processing tweet_id: 1363927198751748097 with label: false
Processing tweet_id: 1341705827548327936 with label: false
Processing tweet_id: 1372916431487172614 with label: false
Processing tweet_id: 1339302185750892547 with label: false
Processing tweet_id: 1310923548878397440 with label: false
Processing tweet_id: 1304419304989917186 with label: false
Processing tweet_id: 1216807639780405249 with label: false
Processing tweet_id: 1310647550471557120 with label: false
Processing tweet_id: 1294294867703726081 with label: false
Processing tweet_id: 1324388104887771143 with label: false
Processing tweet_id: 1216821757967044608 with label: false
Processing tweet_id: 1396311260656979970 with label: false
Processing tweet_id: 1437602416136970242 with label: false
Processing tweet_id: 1370392618178387971 with label: false
Processing tweet_id: 1216812320418082816 with label: false
Processing tweet_id: 1257857126007005193 with label: false
Processing tweet_id: 1298293529739964416 with label: false
Processing tweet_id: 1377295800477356037 with label: false
Processing tweet_id: 1187112564783833088 with label: false
Processing tweet_id: 1312497896357470208 with label: false
Processing tweet_id: 1278500902064852992 with label: false
Processing tweet_id: 1312933260142481410 with label: false
Processing tweet_id: 1353160564529311746 with label: false
Processing tweet_id: 1357433004663201802 with label: false
Processing tweet_id: 1426134410794086403 with label: false
Processing tweet_id: 1375926748639019014 with label: false
Processing tweet_id: 1396251172386836483 with label: false
Processing tweet_id: 1411872979206782976 with label: false
Processing tweet_id: 1208422130548912129 with label: false
Processing tweet_id: 1261893058632826880 with label: false
Processing tweet_id: 1424833779781283841 with label: false
Processing tweet_id: 1430386636987244545 with label: false
Processing tweet_id: 1450315266487775237 with label: false
Processing tweet_id: 1369363281182343174 with label: false
Processing tweet_id: 1239264825953456129 with label: false
Processing tweet_id: 1376922538090061827 with label: false
Processing tweet_id: 1251524085659709441 with label: false
Processing tweet_id: 1371696746154356736 with label: false
Processing tweet_id: 1248707653364264967 with label: false
Processing tweet_id: 1298069740418666497 with label: false
Processing tweet_id: 1358057554887270400 with label: false
Processing tweet_id: 1266737566889308160 with label: false
Processing tweet_id: 1203661693827584000 with label: false
Processing tweet_id: 1252466195456045056 with label: false
Processing tweet_id: 1291503317173116930 with label: false
Processing tweet_id: 1367583722065846278 with label: false
Processing tweet_id: 1318403073144913921 with label: false
Processing tweet_id: 1301140863742095362 with label: false
Processing tweet_id: 1303694410216017921 with label: false
Processing tweet_id: 1199954005922848774 with label: false
Processing tweet_id: 1198616119592009729 with label: false
Processing tweet_id: 1337773251246829569 with label: false
Processing tweet_id: 1269654804621479938 with label: false
Processing tweet_id: 1291546987792343043 with label: false
Processing tweet_id: 1266021004700274690 with label: false
Processing tweet_id: 1267473234821296134 with label: false
Processing tweet_id: 1432166179662143497 with label: false
Processing tweet_id: 1280984431776456705 with label: false
Processing tweet_id: 1305179078060838913 with label: false
Processing tweet_id: 1309531096372183042 with label: false
Processing tweet_id: 1363988459086483456 with label: false
Processing tweet_id: 1361821049730584577 with label: false
Processing tweet_id: 1299382969480679426 with label: false
Processing tweet_id: 1205624164754841600 with label: false
Processing tweet_id: 1304037130402922496 with label: false
Processing tweet_id: 1281615540130328576 with label: false
Processing tweet_id: 1330529128882319371 with label: false
Processing tweet_id: 1217249789613658112 with label: false
Processing tweet_id: 1450142828802289664 with label: false
Processing tweet_id: 1251690304429752323 with label: false
Processing tweet_id: 1381268148771565570 with label: false
Processing tweet_id: 1195057287288754181 with label: false
Processing tweet_id: 1263210686475145216 with label: false
Processing tweet_id: 1251278819828391936 with label: false
Processing tweet_id: 1273960627074187265 with label: false
Processing tweet_id: 854495625911685120 with label: false
Processing tweet_id: 1275073219452522496 with label: false
Processing tweet_id: 1188287266281705472 with label: false
Processing tweet_id: 1263812675949211651 with label: false
Processing tweet_id: 1253897522319425542 with label: true
Processing tweet_id: 1329441383430680577 with label: true
Processing tweet_id: 1364931092382441475 with label: true
Processing tweet_id: 1212540991518978048 with label: true
Processing tweet_id: 1246815716550066176 with label: true
Processing tweet_id: 1437732248133021698 with label: true
Processing tweet_id: 1363672564636274689 with label: true
Processing tweet_id: 1310982360947716097 with label: true
Processing tweet_id: 1374549118752845824 with label: true
Processing tweet_id: 1380536389184458752 with label: true
Processing tweet_id: 1280133024437489664 with label: true
Processing tweet_id: 1309226034210975744 with label: true
Processing tweet_id: 1394050046103101443 with label: true
Processing tweet_id: 1364762313845317635 with label: true
Processing tweet_id: 1278048451868180487 with label: true
Processing tweet_id: 1377392891887120385 with label: true
Processing tweet_id: 1258926872941006848 with label: true
Processing tweet_id: 1247526704358146055 with label: true
Processing tweet_id: 1248690536745238535 with label: true
Processing tweet_id: 1358636412740984832 with label: true
Processing tweet_id: 1348076116188266499 with label: true
Processing tweet_id: 1274909414462500865 with label: true
Processing tweet_id: 1210750688981962753 with label: true
Processing tweet_id: 1417886510674808835 with label: true
Processing tweet_id: 1237188811966361600 with label: true
Processing tweet_id: 1288301468978761729 with label: true
Processing tweet_id: 1270688631686967296 with label: true
Processing tweet_id: 1312198210148986880 with label: true
Processing tweet_id: 1217850717123334146 with label: true
Processing tweet_id: 1245447626344075264 with label: true
Processing tweet_id: 1338254643802087425 with label: true
Processing tweet_id: 1374083928626237442 with label: true
Processing tweet_id: 1354517504761204736 with label: true
Processing tweet_id: 1356403198572044297 with label: true
Processing tweet_id: 1280522726717956098 with label: true
Processing tweet_id: 1386467966414430211 with label: true
Processing tweet_id: 1358799834300485635 with label: true
Processing tweet_id: 1406695845370736648 with label: true
Processing tweet_id: 1382387987728769032 with label: true
Processing tweet_id: 1332528772122284033 with label: true
Processing tweet_id: 1250466552253685763 with label: true
Processing tweet_id: 1326976861327470592 with label: true
Processing tweet_id: 1274921303963840525 with label: true
Processing tweet_id: 1437538934347730947 with label: true
Processing tweet_id: 1249525325433880580 with label: true
Processing tweet_id: 1264106349073498113 with label: true
Processing tweet_id: 1320562078319550466 with label: true
Processing tweet_id: 1337077691300851716 with label: true
Processing tweet_id: 1374025464327602179 with label: true
Processing tweet_id: 1389249899632500736 with label: true
Processing tweet_id: 1204572960452952064 with label: true
Processing tweet_id: 1311030087320514560 with label: true
Processing tweet_id: 1275567647464271872 with label: true
Processing tweet_id: 1368264617340895234 with label: true
Processing tweet_id: 1251156989771517957 with label: true
Processing tweet_id: 1445401436423131141 with label: true
Processing tweet_id: 1257836153933307904 with label: true
Processing tweet_id: 1296130156592013312 with label: true
Processing tweet_id: 1303620299141926912 with label: true
Processing tweet_id: 1279565155219709954 with label: true
Processing tweet_id: 1367234890731773952 with label: true
Processing tweet_id: 1299382794523729920 with label: true
Processing tweet_id: 1310257253916737536 with label: true
Processing tweet_id: 1191369885806448641 with label: true
Processing tweet_id: 1394829454296424451 with label: true
Processing tweet_id: 1396669493116612608 with label: true
Processing tweet_id: 1237214755129102336 with label: true
Processing tweet_id: 1439682136697671683 with label: true
Processing tweet_id: 1364993117787738115 with label: true
Processing tweet_id: 1268168495126241281 with label: true
Processing tweet_id: 1313726020244123649 with label: true
Processing tweet_id: 1208308764178292736 with label: true
Processing tweet_id: 1307881182097559552 with label: true
Processing tweet_id: 1271617183332929536 with label: true
Processing tweet_id: 1312208582335582211 with label: true
Processing tweet_id: 1307112590724739073 with label: true
Processing tweet_id: 1429979674394996738 with label: true
Processing tweet_id: 1262533319335575560 with label: true
Processing tweet_id: 1189291617238298624 with label: true
Processing tweet_id: 1270390346569187329 with label: true
Processing tweet_id: 1250784797737324544 with label: true
Processing tweet_id: 1318053189594263552 with label: true
Processing tweet_id: 1362427362701414404 with label: true
Processing tweet_id: 1215464348686192640 with label: true
Processing tweet_id: 1255985494195949570 with label: true
Processing tweet_id: 1251578393579175936 with label: true
Processing tweet_id: 1327043661461385218 with label: true
Processing tweet_id: 1316094873444003840 with label: true
Processing tweet_id: 1293196786761371650 with label: true
Processing tweet_id: 1252337871446573056 with label: true
Processing tweet_id: 1446863517819326467 with label: true
Processing tweet_id: 1366385502123929600 with label: true
Processing tweet_id: 1251600920166780929 with label: true
Processing tweet_id: 1241413446375260160 with label: true
Processing tweet_id: 1259185943082414080 with label: true
Processing tweet_id: 1307834093518893057 with label: true
Processing tweet_id: 1218160910453366785 with label: true
Processing tweet_id: 1296451264306348032 with label: true
Processing tweet_id: 1208939601039151104 with label: true
Processing tweet_id: 1208473946301091840 with label: true
Processing tweet_id: 1346030479112331265 with label: true
Processing tweet_id: 1246206711209263110 with label: true
Processing tweet_id: 1369108855100219395 with label: true
Processing tweet_id: 1300188395424165888 with label: true
Processing tweet_id: 1249378659489759232 with label: true
Processing tweet_id: 1301607903850356737 with label: true
Processing tweet_id: 1274005036805341184 with label: true
Processing tweet_id: 1370420106057166858 with label: true
Processing tweet_id: 1301858951315820546 with label: true
Processing tweet_id: 1268649520281370628 with label: true
Processing tweet_id: 1296319144447676417 with label: true
Processing tweet_id: 1267151214447378432 with label: true
Processing tweet_id: 1245713490834345984 with label: true
Processing tweet_id: 1266030489250541568 with label: true

In [15]:
len(big_dataframe_dict)

101045

In [16]:
big_df = pd.DataFrame.from_dict(big_dataframe_dict, orient="index")

In [17]:
big_df

,index,is_root,label,tree_id,text
1299150874774831106,0,True,false,1299150874774831106,Esto es el colmo:\nVíctor Manoli dueño de empr...
1299156214069317636,1,False,n/a,1299150874774831106,@hernan_sr @Eneatipo7 Uy k raro 🙄
1299156316770963458,2,False,n/a,1299150874774831106,@hernan_sr No tienen verguenza. Que asco me da...
1299158535805304832,3,False,n/a,1299150874774831106,"@hernan_sr Anciano decrépito ,cuanto te que de..."
1299159444501213184,4,False,n/a,1299150874774831106,@hernan_sr Está la pura cagada en el gobierno ...
...,...,...,...,...,...
1267349731489038338,915,False,n/a,1266030489250541568,@T13 Y que.menos con la terrible falta de conc...
1267350520420859904,916,False,n/a,1266030489250541568,@SofiaCr86963636 @T13 Ja ja entonces felicitem...
1267445948923416576,917,False,n/a,1266030489250541568,@T13 Grande Mañalich y Piñera....y a la gente ...
1267845244734902273,918,False,n/a,1266030489250541568,@T13 Entoces nosotros inventamos la enfermedad...
1274211922527825922,919,False,n/a,1266030489250541568,@vladimirjoelfu2 Y? Así que Canal 13 es un nid...

!python -m spacy download es_core_news_lg

In [19]:
nlp = spacy.load("es_core_news_lg")
# nlp.disable_pipes("parser")

In [20]:
def procesar_texto(texto):
    doc = nlp(texto)
    n_palabras = len([token for token in doc if not token.is_punct])
    n_oraciones = len(list(doc.sents))
    prom_oracion = n_palabras / n_oraciones if n_oraciones > 0 else 0
    return {
        "n_palabras": n_palabras,
        "n_oraciones": n_oraciones,
        "prom_oracion": prom_oracion,
    }

In [21]:
big_df_metrics = big_df["text"].apply(procesar_texto).apply(pd.Series)

In [22]:
big_df = pd.concat([big_df, big_df_metrics], axis=1)

In [30]:
big_df.groupby(["tree_id"]).mean(["n_palabras"]).sort_values(
    by="n_palabras", ascending=False
)

                     index   is_root  n_palabras  n_oraciones  prom_oracion
tree_id
1299382969480679426    0.5  0.500000   39.500000     3.000000     13.000000
1215464348686192640   14.5  0.033333   37.266667     2.366667     19.815556
1251600920166780929    2.5  0.166667   36.166667     1.333333     31.833333
1367234890731773952    1.0  0.333333   34.666667     2.666667     14.000000
1369108855100219395    3.5  0.125000   32.875000     2.875000     11.541667
...                    ...       ...         ...          ...           ...
1301140863742095362   85.0  0.005848    9.385965     1.374269      7.387914
1419760933656739844  549.0  0.000910    8.351228     1.328480      6.340461
1367583722065846278    8.0  0.058824    8.000000     1.235294      6.676471
1430686841540390912   12.0  0.040000    7.680000     1.280000      5.886667
1294294867703726081   13.0  0.037037    7.629630     1.222222      6.364198

[214 rows x 5 columns]

In [33]:
big_df.to_pickle("bigdf.pkl")

In [35]:
print(os.getcwd())

/workspace/rumor-detection/notebooks